openapi: 3.0.0
info:
  title: Movie API
  description: Simple API created for POSTing and GETting movies
  version: 1.0.0
paths:
  /movies:
    get:
      summary: Returns a list of movies.
      tags:
        - movie
      responses:
        "200": # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Movie"
    post:
      summary: Posts new movie into database
      tags:
        - movie
      requestBody:
        description: You have to set `title` in JSON format
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: Title of the movie to be added
      responses:
        "201":
          description: A JSON representation of added movie
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Movie"
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Movie:
      type: object
      properties:
        _id:
          type: integer
          description: ID of movie record in database.
        createdBy:
          type: string
          description: ID of user who created movie.
        createdAt:
          type: string
          description: month and year of movie creation
        title:
          type: string
          description: title of movie
        released:
          type: string
          description: date when movie was released
        genre:
          type: array
          items:
            type: string
          description: array of movie genres
        director:
          type: string
          description: name of movie director
security:
  - bearerAuth: []
